hero/config/routes.rb
Rails.application.routes.draw do
  resources :videos

  get 'pages/about' #this will fetch the html from app/views/pages/about.html.erb

  get 'pages/contact'

end

hero/app/models/video.rb
class Video < ActiveRecord::Base
end

hero/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hero/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

hero/app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index #first function to get executed
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title)
    end
end

hero/app/helpers/application_helper.rb
module ApplicationHelper
end

hero/app/helpers/pages_helper.rb
module PagesHelper
end

hero/app/helpers/videos_helper.rb
module VideosHelper
end

hero/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code4Newbies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>

</head>
<body>

	<nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Code4Newbies</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#"><i class="mdi-action-view-list"></i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="#"><i class="mdi-action-view-list"></i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
      </ul>
    </div>
  </nav>

	<div class="row">
		<div class="col m10 offset-m1">
			<%= yield %>
		</div>
	</div>

	<script>
		$(".button-collapse").sideNav();
	</script>

</body>
</html>

hero/app/views/pages/about.html.erb
<h3> About Me </h3>

<div class="card z-depth-3">
	<div class="card-content white-text">
		<div class="col m6">
      <a class="twitter-timeline" href="https://twitter.com/silvan_frank" data-widget-id="671400331369127936">Tweets by @silvan_frank</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
		<div class="col m6">
			<div class="card-panel grey lighten-5 z-depth-1">
				<div class="row valign-wrapper">
					<div class="col m3">
						<%= image_tag "avatar.png", class: "circle responsive-img" %>
					</div>
					<div class="col m9">
						<span class="black-text">
							I don't know what to say. Let the world tell you more... :)
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

hero/app/views/pages/contact.html.erb
<h3> Contact </h3>

<div class="card z-depth-3">
  <div class="card-content">
    <p>
      Do you wanna talk.. <br>
      <div id="map"></div>
    </p>
  </div>
</div>

<style>
      #map {
        width: 100%;
        height: 400px;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map');
        var mapOptions = {
          center: new google.maps.LatLng(44.5403, -78.5463),
          zoom: 14,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
        var marker = new google.maps.Marker({
position: new google.maps.LatLng(44.5403, -78.5463),
title: "Here is Silvan's place"

        });

        marker.setMap(map);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
  </script>

hero/app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wistia %><br>
    <%= f.text_field :wistia %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hero/app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

hero/app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Wistia</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.wistia %></td>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

hero/app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

hero/app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wistia:</strong>
  <%= @video.wistia %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>